#spring.application.name=userservice
#spring:
#  application:
#    name: userservice
#  config:
#    url: jdbc:postgresql://localhost:5432/fitness-micro-user
#    username: postgres
#    password: tintin9
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: tintin9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true